apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
bootstrapTokens:
- token: "9a08jv.c0izipklcatwnze7"
  description: "kubeadm bootstrap token"
  ttl: "0"
- token: "783bde.3f89s0fje9d28fhf"
  description: "another bootstrap token"
  ttl: "0"
  usages:
  - authentication
  - signing
  groups:
  - system:bootstrappers:kubeadm:default-node-token
nodeRegistration:
  name: "k8s-m1.bigsfintech.local"
  criSocket: "/var/run/dockershim.sock"
  taints:
  - key: "kubeadmNode"
    value: "master"
    effect: "NoSchedule"
localAPIEndpoint:
  advertiseAddress: "172.17.0.230"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.3
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
etcd:
  local:
    imageTag: "3.2.26"
    dataDir: "/data/kubernetes/etcd"
controllerManager:
  extraArgs:
    horizontal-pod-autoscaler-use-rest-clients: "true"
    horizontal-pod-autoscaler-sync-period: "10s"
    node-monitor-grace-period: "3m"
apiServer:
  extraArgs:
    service-node-port-range: "1-65535"
    runtime-config: "api/all=true"
  certSANs:
  - "k8s-m1.bigsfintech.local"
controlPlaneEndpoint: "haproxy.bigsfintech.local:6443"
networking:
  serviceSubnet: "172.30.0.0/16"
  podSubnet: "172.31.0.0/16"
  dnsDomain: "cluster.local"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs

