apiVersion: v1
kind: Service
metadata:
  name: mysql-mysql
  namespace: default
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-single
  type: NodePort
