apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-prometheus
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: external-prometheus
  template:
    metadata:
      labels:
        app: external-prometheus
    spec:
      containers:
      - name: external-prometheus
        image: harbor.sxkj.online/app/prom/prometheus:v2.10.0
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
        - /bin/prometheus
        - --config.file=/etc/prom/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --web.console.libraries=/usr/share/prometheus/console_libraries
        - --web.console.templates=/usr/share/prometheus/consoles
        resources:
          limits:
            cpu: 5000m
            memory: 8192Mi
          requests:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: prometheus-blk
          mountPath: /prometheus
        - name: prometheus-cfg
          mountPath: /etc/prom/
      volumes:
      - name: prometheus-blk
        persistentVolumeClaim:
          claimName: external-prometheus-1
      - name: prometheus-cfg
        configMap:
          defaultMode: 0644
          name: external-prometheus-cm
