apiVersion: v1
kind: Service
metadata:
  name: external-prometheus-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - name: prom
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: external-prometheus

