apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-prometheus-1
  namespace: default
spec:
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
