apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-orientdb-one
spec:
  volumeMode: Filesystem
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-orientdb-one-backup
spec:
  volumeMode: Filesystem
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
