apiVersion: v1
kind: Service
metadata:
  name: orientdb-client
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 2480
    protocol: TCP
    targetPort: 2480
  - name: binary
    port: 2424
    protocol: TCP
    targetPort: 2424
  selector:
    app: orientdb-one
