apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-replicaset
    chart: mongodb-replicaset-3.9.2
    heritage: Tiller
    release: mongo
  name: mongodb
  namespace: default
spec:
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb-replicaset
    release: mongo
    statefulset.kubernetes.io/pod-name: mongo-mongodb-replicaset-1
  type: ClusterIP
