replicas: 3
port: 27017

replicaSetName: rs0

podDisruptionBudget: {}
  # maxUnavailable: 1
  # minAvailable: 2

auth:
  enabled: true
  adminUser: admin
  adminPassword: fFbi4Z3MJf4bj7rTDiCL
  metricsUser: metrics
  metricsPassword: fqkwabqMrLdp16Qs5KFt
  key: 30ZAduoik7VDv91ZRiCyEKOu6aJH3/j8VAOW0G57fNiu4dv6qWW6v8fJpTLPT35WtPl0119ji2SdHLAulzHfZuc7fpuedFLU3OLufIB9geAMaCr+xAn+yAQIgUIKi4p/D8UjKM8B6hCY6QoXUfYaO+clAUCsgq3ne8mq/9+ljoHggfqEUVQCgRSxDorgSxtrZOY4JWhjIjWXPe9GlkIuhw6LK9tmcyaJKH23qH9syGMWGB2gkVulnvzVS65A7m0mSs2eeMPgdhoMRycBvp+S65wR1Z2HRVyfayKnpXztshpjLrWCVDrFH2tg88xtz/UMp7lhn4L7eZzNYhVbJO/IkrhoH/L1qO+2Ag4GhXKiuU87iIq1ShHn5n+BKIX+UAMUOWtaiZFMdx4y7dP4a1erZ7r6xcuTwz2DMlQugHE0jmV+Wv/scpIASXmtroWXGQhAjPd/6ROY3I0/rYBDsHqAmKAmUV0eENTgECXPgrOU4AdwIdvP4Z/CXSCxGBSF27ZIKS/AIkreLesy7a6KoW5F5J6W9RF92hFcGQP143xCh32n2WXjHT4S4aZPP2kr8AXg6JzvMcrPaKP+SaBz3o4MwfZDVxmnpS7/u1WQft2x7zPQq3ra9eNCZoOaSVjYzQw2IacjKP6gI55iJ71gQEg5+yRK+87tqQObSjleKn49OMCeg78PRcJxhwwEzpRW3YsEm1DkPiPB/Y3Gx/MNZqNFn9O/rHL1J2gLPdxXBCjOWunSGMIfUnVtu2tnt2FpU8TsqMnmpyX+v/mjD8CT0vMBVluEqcxQC7HrNBCz2ZGuAl7niqI6i6W0/w4gRdfzn1WgNs8jhkq7K/NPcbGCGi+H3WcViKfVZKMrmObA/e+mFF8tcNypJePBwVFLRZjvWtIFfyTgrB21tmDf4E4Mj12c5DNtp996JL+ZVavAfCxGFw43p8xlvVC7h9i7jLdfCYa+vjiNuto91u7EfMJGlF9fLrZ8uTf/NSGaZTnkfapQAXf9lAi
  # existingKeySecret:
  # existingAdminSecret:
  # existingMetricsSecret:

## Optionally specify an array of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []
#   - myRegistrKeySecretName

# Specs for the Docker image for the init container that establishes the replica set
installImage:
  repository: harbor.sxkj.online/app/unguiculus/mongodb-install
  tag: 0.7
  pullPolicy: IfNotPresent

# Specs for the Docker image for the copyConfig init container
copyConfigImage:
  repository: harbor.sxkj.online/app/busybox
  tag: 1.29.3
  pullPolicy: IfNotPresent

# Specs for the MongoDB image
image:
  repository: harbor.sxkj.online/app/mongo
  tag: 3.6
  pullPolicy: IfNotPresent

# Additional environment variables to be set in the container
extraVars: {}
# - name: TCMALLOC_AGGRESSIVE_DECOMMIT
#   value: "true"

# Prometheus Metrics Exporter
metrics:
  enabled: true
  image:
    repository: harbor.sxkj.online/app/ssalaues/mongodb-exporter
    tag: 0.6.1
    pullPolicy: IfNotPresent
  port: 9216
  path: "/metrics"
  socketTimeout: 3s
  syncTimeout: 1m
  prometheusServiceDiscovery: true
  resources: {}

# Annotations to be added to MongoDB pods
podAnnotations: {}

securityContext:
  enabled: true
  runAsUser: 999
  fsGroup: 999
  runAsNonRoot: true

init:
  resources: {}
  timeout: 900

resources: {}
# limits:
#   cpu: 500m
#   memory: 512Mi
# requests:
#   cpu: 100m
#   memory: 256Mi

## Node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

affinity: {}

tolerations: []

extraLabels: {}

# priorityClassName: ""

persistentVolume:
  enabled: true
  ## mongodb-replicaset data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}

# Annotations to be added to the service
serviceAnnotations: {}

terminationGracePeriodSeconds: 30

tls:
  # Enable or disable MongoDB TLS support
  enabled: false
  # Please generate your own TLS CA by generating it via:
  # $ openssl genrsa -out ca.key 2048
  # $ openssl req -x509 -new -nodes -key ca.key -days 10000 -out ca.crt -subj "/CN=mydomain.com"
  # After that you can base64 encode it and paste it here:
  # $ cat ca.key | base64 -w0
  # cacert:
  # cakey:

# Entries for the MongoDB config file
configmap: {}

# Javascript code to execute on each replica at initContainer time
# This is the recommended way to create indexes on replicasets.
# Below is an example that creates indexes in foreground on each replica in standalone mode.
# ref: https://docs.mongodb.com/manual/tutorial/build-indexes-on-replica-sets/
# initMongodStandalone: |+
#   db = db.getSiblingDB("mydb")
#   db.my_users.createIndex({email: 1})

# Readiness probe
readinessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 1
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1

# Liveness probe
livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
