apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-wuhan-view
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-with-exec
subjects:
- kind: ServiceAccount
  name: wuhan-view
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-wuhan-view
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-with-exec
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: wuhan-view
