apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-single-ceph-conf
  namespace: default
data:
  my.cnf: |
    [mysqld]
    server-id=1
    pid-file=/var/run/mysqld/mysqld.pid
    socket=/var/run/mysqld/mysqld.sock
    datadir=/var/lib/mysql
    log-bin=mysql-bin
    log-error=/var/log/mysql/error.log
    default_authentication_plugin=mysql_native_password
    basedir=/var/lib/mysql
    port=3306
    #tmpdir=/var/lib/mysql/tmp
    max-allowed-packet=16M
    bind-address=0.0.0.0
    character-set-server=UTF8
    collation-server=utf8_general_ci
    innodb-file-per-table=1
    innodb-file-format=Barracuda
    sql-mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    explicit-defaults-for-timestamp=0
    max-connect-errors=1000
    max-connections=1000
    wait-timeout=86400
    innodb-buffer-pool-size=17179869184
    slow-query-log=on
    long-query-time=10
