apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-single-ceph
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-single-ceph
  template:
    metadata:
      labels:
        app: mysql-single-ceph
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: mysql-single-ceph
        image: harbor.sxkj.online/app/mysql:5.7.26
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "POCZsdd9Cft9SS2Zvepe"
        ports:
        - containerPort: 3306
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          timeoutSeconds: 5
        volumeMounts:
        - name: mysql-conf
          mountPath: /etc/mysql/mysql.conf.d/
        - name: ceph-dir
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-conf
        configMap:
          name: mysql-single-ceph-conf
          items:
          - key: my.cnf
            path: my.cnf
      - name: ceph-dir
        persistentVolumeClaim:
          claimName: mysql-one-data

