apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-one-data
spec:
  volumeMode: Filesystem
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
