apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: default
  labels:
    app: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: sentinel
    port: 26379
    targetPort: 26379
  selector:
    app: redis-ha
    release: redis
    statefulset.kubernetes.io/pod-name: redis-redis-ha-server-1
