apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: centos
  name: centos
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: centos
        image: harbor.sxkj.online/baseimage/centos:7.6.1810
        command:
        - bash
        - -c
        - sleep 86400
#        livenessProbe:
#          tcpSocket:
#            port: 8080
#          initialDelaySeconds: 2
#          failureThreshold: 3
#          timeoutSeconds: 30
#        readinessProbe:
#          initialDelaySeconds: 2
#          successThreshold: 2
#          timeoutSeconds: 10
#          failureThreshold: 3
#          periodSeconds: 10
#          httpGet: 
#            path: /centos/check
#            port: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 200m
            memory: 300Mi
