apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
    chart: mysql-4.5.2
    component: master
    heritage: Tiller
    release: mysql
  name: mysql-mysql
  selfLink: /api/v1/namespaces/default/services/mysql-mysql
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  - name: metrics
    port: 9104
    protocol: TCP
    targetPort: metrics
  selector:
    app: mysql
    component: master
    release: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
