apiVersion: v1
kind: Service
metadata:
  name: mysql-external-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
    component: master
    release: mysql
