apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-we-electronic
  namespace: electronic-hardware
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-with-exec
subjects:
- kind: ServiceAccount
  name: we-electronic
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-we-electronic
  namespace: electronic-hardware
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-with-exec
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: we-electronic
